In [1]:
import matplotlib.pyplot as plt
import numpy as np
import sklearn
from sklearn.linear_model import LinearRegression
import tensorflow
from tensorflow import keras 
import random
import scipy


/home/users/t_wand01/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/users/t_wand01/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/users/t_wand01/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/users/t_wand01/.local/lib/python3.7/site-packages/tensorflow/

In [4]:
# load json and create model
json_file = open('NN_Lorenz_dotX0.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = keras.models.model_from_json(loaded_model_json)
# load weights into new model
loaded_model.load_weights("NN_Lorenz_dotX0.tf")

In [5]:
# load json and create model
json_file = open('NN_Lorenz_dotX1.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model1 = keras.models.model_from_json(loaded_model_json)
# load weights into new model
loaded_model1.load_weights("NN_Lorenz_dotX1.tf")

In [6]:
# load json and create model
json_file = open('NN_Lorenz_dotX2.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model2 = keras.models.model_from_json(loaded_model_json)
# load weights into new model
loaded_model2.load_weights("NN_Lorenz_dotX2.tf")

In [7]:
loaded_model.predict(np.ones(3).reshape(1,-1))

array([[0.0629824]], dtype=float32)

In [8]:
loaded_model1.predict(np.ones(3).reshape(1,-1))

array([[0.11776029]], dtype=float32)

In [9]:
loaded_model2.predict(np.ones(3).reshape(1,-1))

array([[-0.05398235]], dtype=float32)